config/routes.rb
# This file is a part of Redmine Invoices (redmine_contacts_invoices) plugin,
# invoicing plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# https://www.redmineup.com/
#
# redmine_contacts_invoices is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts_invoices is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts_invoices.  If not, see <http://www.gnu.org/licenses/>.

resources :invoices do
  member do
    get :client_view
  end
  collection do
    get :auto_complete
    get :bulk_edit, :context_menu
    post :bulk_edit, :bulk_update
    delete :bulk_destroy
    get :recurring
  end
end

resources :recurring_invoices

resources :invoices do
  resources :invoice_payments, :as => :payments
end

resources :invoice_payments, :only => [:show, :index]
resources :invoice_comments, :only => [:create, :destroy]

resources :projects do
resources :invoices, :only => [:index, :new, :create]
end

match "invoice_time_entries/new", :controller => "invoice_time_entries", :action => 'new', :via => :get
match "invoice_time_entries/create", :controller => "invoice_time_entries", :action => 'create', :via => :post

app/helpers/invoices_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine Invoices (redmine_contacts_invoices) plugin,
# invoicing plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# https://www.redmineup.com/
#
# redmine_contacts_invoices is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts_invoices is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts_invoices.  If not, see <http://www.gnu.org/licenses/>.

module InvoicesHelper
  include RedmineInvoices::InvoiceReports
  include Redmine::I18n

  def invoices_contacts_for_select(project, options={})
    scope = Contact.where(options[:where])
    scope = scope.joins(:projects).uniq.where(Contact.visible_condition(User.current))
    scope = scope.joins(:invoices)
    scope = scope.where("(#{Project.table_name}.id <> -1)")
    scope = scope.where(:invoices => {:project_id => project}) if project
    scope = scope.limit(options[:limit] || 500)
    scope.to_a.sort!{|x, y| x.name <=> y.name }.collect {|m| [options[:short_label] ? m.name : m.name_with_company, m.id.to_s]}
  end

  def invoice_status_tag(invoice)
    status_tag = content_tag(:span, invoice_status_name(invoice.status_id))
    content_tag(:span, status_tag, :class => "tag-label-color invoice-status #{invoice_status_name(invoice.status_id, true).to_s}")
  end

  def invoice_status_url(status_id, options={})
    {:controller => 'invoices',
     :action => 'index',
     :set_filter => 1,
     :project_id => @project,
     :fields => [:status_id],
     :values => {:status_id => [status_id]},
     :operators => {:status_id => '='}}.merge(options)
  end

  def invoice_tag(invoice)
    invoice_title = "##{invoice.number} - #{format_date(invoice.invoice_date)}"
    s = ''
    if invoice.visible?
      s << link_to(invoice_title, invoice_path(invoice), :class => 'icon icon-invoice', :download => true)
      s << " " + link_to(image_tag('page_white_acrobat_context.png', :plugin => "redmine_contacts_invoices"), invoice_path(invoice, :format => 'pdf'))
      s << " " + content_tag(:span, content_tag(:strong, invoice.amount_to_s), :class => "amount")
    else
      s << content_tag(:span, invoice_title, :class => 'icon icon-invoice')
    end
    s << " - #{invoice.subject}" unless invoice.subject.blank?
    s << " " + content_tag(:span, '(' + invoice.contact.name + ')', :class => 'contact') if invoice.contact
    s
  end

  def group_invoice_tag(invoice)
    invoice_title = "##{invoice.number} - #{format_date(invoice.invoice_date)}"
    s =
      if invoice.visible?
        link_to(invoice_title, invoice_path(invoice), :class => 'icon icon-invoice')
      else
        content_tag(:span, invoice_title, :class => 'icon icon-invoice')
      end
    s.html_safe
  end

  def contact_custom_fields
    if "ContactCustomField".is_a_defined_class?
      ContactCustomField.where("#{ContactCustomField.table_name}.field_format = 'string' OR #{ContactCustomField.table_name}.field_format = 'text'").map{|f| [f.name, f.id.to_s]}
    else
      []
    end
  end

  def invoices_list_styles_for_select
    list_styles = [[l(:label_crm_list_excerpt), "list_excerpt"]]
  end

  def invoices_list_style
    list_styles = invoices_list_styles_for_select.map(&:last)
    if params[:invoices_list_style].blank?
      list_style = list_styles.include?(session[:invoices_list_style]) ? session[:invoices_list_style] : InvoicesSettings.default_list_style
    else
      list_style = list_styles.include?(params[:invoices_list_style]) ? params[:invoices_list_style] : InvoicesSettings.default_list_style
    end
    session[:invoices_list_style] = list_style
  end

  def expenses_list_style
    'list_excerpt'
  end


  def invoice_lang_options_for_select(has_blank=true)
    (has_blank ? [["(auto)", ""]] : []) +
      RedmineInvoices.available_locales.collect{|lang| [ ll(lang.to_s, :general_lang_name), lang.to_s]}.sort{|x,y| x.last <=> y.last }
  end

  def invoice_avaliable_locales_hash
    Hash[*invoice_lang_options_for_select.collect{|k, v| [v.blank? ? "default" : v, k]}.flatten]
  end

  def collection_invoice_status_names
    [[:draft, Invoice::DRAFT_INVOICE],
     [:estimate, Invoice::ESTIMATE_INVOICE],
     [:sent, Invoice::SENT_INVOICE],
     [:paid, Invoice::PAID_INVOICE],
     [:canceled, Invoice::CANCELED_INVOICE]]
  end

  def invoice_number_format(number)
    ActionController::Base.helpers.number_with_delimiter(number,
        :separator => ContactsSetting.decimal_separator,
        :delimiter => ContactsSetting.thousands_delimiter)
  end

  def collection_invoice_statuses
    Invoice::STATUSES.map{|k, v| [l(v), k]}
  end

  def collection_invoice_statuses_for_select
    collection_invoice_statuses.select{|s| s[1] != Invoice::PAID_INVOICE}
  end

  def collection_invoice_statuses_for_filter(status_id=nil)
    collection = collection_invoice_statuses.map{|s| [s[0], s[1].to_s]}
    collection.push [l(:label_invoice_overdue), "d"]
    collection.insert 0, [l(:label_open_issues), "o"]
    collection.insert 0, [l(:label_all), ""]
    collection
  end

  def label_with_currency(label, currency)
    l(label).mb_chars.capitalize.to_s + (currency.blank? ? '' : " (#{currency})")
  end

  def invoice_status_name(status, code=false)
    return (code ? "draft" : l(:label_invoice_status_draft)) unless collection_invoice_statuses.map{|v| v[1]}.include?(status)

    status_data = collection_invoice_statuses.select{|s| s[1] == status }.first[0]
    status_name = collection_invoice_status_names.select{|s| s[1] == status}.first[0]
    return (code ? status_name : status_data)
  end

  def collection_for_discount_types_select
    [:percent, :amount].each_with_index.collect{|l, index| [l("label_invoice_#{l.to_s}".to_sym), index]}
  end

  def link_to_remove_invoice_fields(name, f, options={})
    f.hidden_field(:_destroy) + link_to_function(name, "remove_invoice_fields(this)", options)
  end

  def discount_label(invoice)
    "#{l(:field_invoice_discount)} (#{"%2.f" % invoice.discount}%)"
  end

  def link_to_add_invoice_fields(name, f, association, options={})
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_invoice_fields(this, '#{association}', '#{escape_javascript(fields)}')", options={})
  end

  def retrieve_invoices_query
    # debugger
    # params.merge!(session[:invoices_query])
    # session[:invoices_query] = {:project_id => @project.id, :status_id => params[:status_id], :category_id => params[:category_id], :assigned_to_id => params[:assigned_to_id]}

    if  params[:status_id] || !params[:contact_id].blank? || !params[:assigned_to_id].blank? || !params[:period].blank?
      session[:invoices_query] = {:project_id => (@project ? @project.id : nil),
                                  :status_id => params[:status_id],
                                  :contact_id => params[:contact_id],
                                  :period => params[:period],
                                  :assigned_to_id => params[:assigned_to_id]}
    else
      if api_request? || params[:set_filter] || session[:invoices_query].nil? || session[:invoices_query][:project_id] != (@project ? @project.id : nil)
        session[:invoices_query] = {}
      else
        params.merge!(session[:invoices_query])
      end
    end
  end

  def is_no_filters
    (params[:status_id] == 'o' && params[:assigned_to_id].blank? && (params[:period].blank? || params[:period] == 'all') && (params[:paid_period].blank? || params[:paid_period] == 'all') && (params[:due_date].blank? || params[:due_date] == 'all') && params[:contact_id].blank?)
  end

  def is_date?(str)
    temp = str.gsub(/[-.\/]/, '')
    ['%m%d%Y','%m%d%y','%M%D%Y','%M%D%y'].each do |f|
      begin
        return true if Date.strptime(temp, f)
      rescue
           #do nothing
      end
    end
  end

  def due_days(invoice)
    return "" if invoice.due_date.blank? || invoice.status_id != Invoice::SENT_INVOICE
    if invoice.due_date.to_date >= Date.today
      content_tag(:span, " (#{l(:label_invoice_days_due, :days => (invoice.due_date.to_date - Date.today).to_s)})", :class => "due-days")
    else
      content_tag(:span, " (#{l(:label_invoice_days_late, :days => (Date.today - invoice.due_date.to_date).to_s)})", :class => "overdue-days")
    end
  end

  def get_contact_extra_field(contact)
    field_id = InvoicesSettings[:invoices_contact_extra_field, @project]
    return "" if field_id.blank?
    return "" unless contact.respond_to?(:custom_values)
    contact.custom_values.find_by_custom_field_id(field_id)
  end

  def invoice_to_pdf(invoice)
    RedmineInvoices::InvoiceReports.invoice_to_pdf_prawn(invoice, RedmineInvoices::TEMPLATE_CLASSIC)
  end

end

app/views/invoices/_attributes.html.erb
<<%= Redmine::VERSION.to_s > '3.2' ? 'div' : 'table' %>  class="attributes invoice status-<%= invoice.status_id %> <%= 'overdue' if invoice.overdue? %>" >
<%= issue_fields_rows do |rows|
  rows.left l(:field_invoice_status), invoice_status_tag(invoice), :class => 'status'
  rows.left l(:field_invoice_language), invoice_avaliable_locales_hash[invoice.language.blank? ? 'default' : invoice.language], :class => 'language'
  rows.left l(:field_invoice_contact), !invoice.contact.blank? ? link_to_contact(invoice.contact, :avatar => true).html_safe : ""
  rows.left l(:field_invoice_assigned_to), "#{avatar(invoice.assigned_to, :size => "14")}#{(invoice.assigned_to ? link_to_user(invoice.assigned_to) : "-")}".html_safe, :class => 'assigned-to'
  rows.right l(:field_invoice_order_number), invoice.order && invoice.order.visible? ? link_to(invoice.order_number, order_path(invoice.order.id)): invoice.order_number, :class => 'oder-number'
  rows.right l(:field_invoice_date), format_date(invoice.invoice_date), :class => 'start-date'
  rows.right l(:field_invoice_due_date), format_date(invoice.due_date), :class => 'due-date'
  rows.right l(:field_invoice_discount), invoice.discount > 0 ? "#{"%.2f"%invoice.discount.round(2)}% / #{price_to_currency(invoice.discount_amount, invoice.currency)}".html_safe : ""
end %>
  <%= call_hook(:view_invoices_show_details_bottom, :invoice => invoice) %>
</<%= Redmine::VERSION.to_s > '3.2' ? 'div' : 'table' %>>

<% if invoice.description? %>
  <hr />
  <p><strong><%=l(:field_description)%></strong></p>
  <div class="wiki">
  <%= textilizable invoice, :description, :attachments => invoice.attachments %>
  </div>
<% end %>

app/views/invoices/_line_description.html.erb
<td class="description">
  <%= textilizable(line.description) %>
</td>

app/views/invoices/_line_fields.html.erb
<tr class="line fields sortable-line" id="line-<%= f.object.id %>">
  <!-- <td><span class="sort icon icon-sort" style="cursor: row-resize;"></span> </td>  -->
  <%= render :partial => 'invoices/line_field_description', :locals => { :f => f } %>
  <td class="quantity"><%= f.text_field :quantity, :no_label => true, :size => 6, :onkeyup => 'updateInvoiceTotal(this)' %></td>
  <% if InvoicesSettings.show_units? %>
  <td class="units"><%= f.text_field :units, :no_label => true, :size => 8 %></td>
  <% end %>
  <td class="price">
    <%= f.text_field :price, :no_label => true, :size => 8, :onkeyup => 'updateInvoiceTotal(this)' %>
    <div class="jstElements invoice-menu" style="display:none;" title="<%= l(:label_invoices_copy_to_all) %>">
        <button type="button" class="icon-money-dollar" onclick="copyPriceToAll(this);">
          <span><%= l(:label_invoices_copy_to_all) %></span>
        </button>
    </div>
  </td>
  <% if !InvoicesSettings.disable_taxes?(@project) || (f.object.invoice.respond_to?(:has_taxes?) && f.object.invoice.has_taxes?)   %>
  <td class="tax">
    <% line_tax = (f.object.new_record? && f.object.tax.blank?) ? ContactsSetting.default_tax : f.object.tax %>
    <%= check_box_tag :show_tax, "1", false, :onclick=>"$(this).hide(); $(this).parent().find('.tax-fields').show(); $(this).next().find('input').focus();  $(this).next().find('input').val('#{ContactsSetting.default_tax}'); return false;" if line_tax.blank? || line_tax == 0 %>
    <span class="tax-fields" style="white-space: nowrap; <%= line_tax.blank? || line_tax == 0 ? "display:none;" : "" %>"><%= f.text_field :tax, :no_label => true, :size => 5, :value => line_tax %>&nbsp;%
    </span>
  </td>
  <% end %>
  <td class="total"><%= format("%.2f\n", f.object.price * f.object.quantity) if f.object.price && f.object.quantity  %></td>
  <td> <%= link_to_remove_invoice_fields "", f, :class => "icon icon-del"  %></td>
  <%= f.hidden_field :position, :class => 'position' %>
</tr>

app/views/invoices/_line_row.html.erb
<tr class="line-data <%= cycle('odd', 'even') %>">
  <td class="position"><%= line.position %></td>
  <%= render :partial => 'invoices/line_description', :locals => {:line => line} %>
  <% InvoiceLine.new.available_custom_fields.each do |custom_field| %>
    <td class="custom_field_<%= custom_field.id %>"><%= simple_format_without_paragraph(show_value(line.custom_value_for(custom_field))) %></td>
  <% end %>
  <td class="quantity">x<%= line.quantity %></td>
  <% if InvoicesSettings.show_units? %>
    <td class="units"><%= line.units %></td>
  <% end %>
  <td class="price"><%= line.price_to_s %></td>
  <% if invoice.has_taxes?  %>
  <td class="tax" title="<%= "#{l(:field_invoice_line_tax_amount)}: #{price_to_currency(line.tax_amount, invoice.currency)}" if line.tax %>"><%= line.tax.to_s + '%' if line.tax.to_f > 0.0 %></td>
  <% end %>
  <td class="total_price"><%= price_to_currency(line.total, invoice.currency) %></td>
</tr>

app/views/invoices/_list_excerpt.html.erb
<%= form_tag({}, :data => {:cm_url => context_menu_invoices_path}) do -%>
	<%= hidden_field_tag 'back_url', url_for(params) %>
	<%= hidden_field_tag 'project_id', @project.id if @project %>
	<div class="autoscroll">
		<table class="contacts invoices index">
		<tbody>
	    <% previous_group = false %>
	    <% @invoices.each do |invoice| %>
	        <% if @query.grouped? && (group = @query.group_by_column.value(invoice)) != previous_group %>
	          <% reset_cycle %>
	          <tr class="group open">
	            <td colspan="<%= @query.columns.size + 2 %>">
	              <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
	              <%= group.blank? ? 'None' : column_content(@query.group_by_column, invoice) %>
								<% if @invoice_count_by_group[group] %>
	              <span class="count">(<%= @invoice_count_by_group[group] %>)</span>
	              <% end %>
	              <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %>
	            </td>
	          </tr>
	          <% previous_group = group %>
	        <% end %>

			<tr class="hascontextmenu">
				<td class="checkbox">
					<%= check_box_tag("ids[]", invoice.id, false, :id => nil)  %>
				</td>
				<td class="status">
				  <%= invoice_status_tag(invoice) %>
				</td>
				<% if invoice.contact %>
				<td class="avatar">
					<%= contact_tag(invoice.contact, :type => :avatar, :size => 32) %>
				</td>
				<% end %>
				<td class="name invoice-name" <%= 'colspan=2' unless invoice.contact %>>
						<h1 class="invoice_number"><%= link_to "#{invoice.number}#{' - ' + invoice.subject unless invoice.subject.blank?}", {:controller => :invoices, :action => :show, :id => invoice.id} %></h1>
						<p>
							<% if invoice.contact.blank? %>
								<%= l(:label_invoice_internal) %>
							<% else %>
								<%= contact_tag(invoice.contact, :type => 'plain') %>
							<% end %>
							<% if invoice.is_paid? %>
								 - <%= l(:label_invoice_status_paid) %>: <%= format_date(invoice.paid_date) %>
							<% elsif invoice.is_open? && invoice.balance > 0 %>
								 - <%= l(:label_invoice_amount_due) %>: <%= price_to_currency(invoice.remaining_balance, invoice.currency) %>
							<% end %>
						</p>
				</td>

				<td class="info invoice-info">
					<div class="invoice-sum"><strong><%= invoice.amount_to_s  %></strong>

					</div>
					<div class="invoice-date" >
						<strong><%# l(:field_invoice_date) + ":" %></strong> <%= format_date(invoice.invoice_date) %><%= due_days(invoice) %>
					</div>
				</td>
			</tr>
	    <% end %>

		</tbody>
	  </table>
	  <table class="contacts invoices index total">
			<tbody>
			<tr class="total">
				<th class="title"><%= l(:label_invoice_amount_due) %>:</th>
				<th class="sum invoices-sum">
					<%= prices_collection_by_currency(@due_amount, :hide_zeros => true).join('<br/>').html_safe %>
				</th>
				<th class="title"><%= l(:label_invoice_status_paid) %>:</th>
				<th class="sum invoices-sum">
					<%= prices_collection_by_currency(@paid_amount, :hide_zeros => true).join('<br/>').html_safe %>
				</th>
				<th class="title"><%= "#{l(:label_total)} (#{@invoices_count})" %>:</th>
				<th class="sum invoices-sum">
					<%= prices_collection_by_currency(@invoiced_amount, :hide_zeros => true).join('<br/>').html_safe %>
				</th>
			</tr>

			</tbody>
	  </table>
	</div>
<% end %>

app/views/invoices/context_menu.html.erb
<ul>

	<% if @invoice.present? %>
		<li><%= context_menu_link l(:button_edit), {:controller => 'invoices', :action => 'edit', :id => @invoice}, :class => 'icon-edit', :disabled => !@can[:edit] %></li>
    <li><%= context_menu_link l(:label_invoice_pdf), {:controller => 'invoices', :action => 'show', :format => 'pdf', :id => @invoice}, :class => 'icon-pdf-context', :disabled => !@can[:pdf] %></li>
    <li><%= context_menu_link l(:label_invoice_add_payment), new_invoice_payment_path(:invoice_id => @invoice), :class => 'icon icon-add-payment', :disabled => !User.current.allowed_to?(:edit_invoice_payments, @invoice.project) %></li>
	<% else %>
    <!-- <li><%# context_menu_link l(:button_edit), {:controller => 'invoices', :action => 'bulk_edit', :ids => @invoices.collect(&:id)},
            :class => 'icon-edit', :disabled => !@can[:edit] %></li> -->
	<% end %>

    <% unless @project.nil? -%>
		<li class="folder">
			<a href="#" class="submenu"><%= l(:field_status) %></a>
			<ul>
			<% collection_invoice_statuses_for_select.each do |u| -%>
			    <li><%= context_menu_link u[0], {:controller => 'invoices', :action => 'bulk_update', :ids => @invoices.collect(&:id), :invoice => {'status_id' => u[1]}, :back_url => @back}, :method => :post,
			                              :selected => (@invoice && u[1] == @invoice.status_id), :disabled =>  !@can[:change_status] %></li>
			<% end -%>
			</ul>
		</li>
	<% end %>

  <li><%= context_menu_link l(:button_delete), {:controller => 'invoices', :action => 'bulk_destroy', :ids => @invoices.collect(&:id), :project_id => @project, :back_url => @back},
                            :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon-del', :disabled => !@can[:delete] %>
  </li>
</ul>

app/views/invoices/edit.html.erb
<h2><%= l(:label_invoice_edit) %></h2>

<%= labelled_form_for :invoice, @invoice, :url => {:action => 'update', :id => @invoice.id}, :html => { :multipart => true, :method => :put, :id => 'invoice_form'} do |f|  %>
  <%= render :partial => 'form', :locals => {:f => f, :invoice => @invoice}  %>
  <%= submit_tag l(:button_save) -%>
<% end -%>

<% content_for :header_tags do %>
  <%= select2_assets %>
  <%= javascript_include_tag :invoices, :plugin => 'redmine_contacts_invoices'  %>
<% end %>

app/views/invoices/show.html.erb
<div class="contextual">
	<% replace_watcher ||= 'watcher' %>
	<%= watcher_tag(@invoice, User.current, {:id => replace_watcher, :replace => ['watcher','watcher2']}) if false %>
	<%= link_to l(:button_edit), {:controller => 'invoices', :action => 'edit', :id => @invoice}, :class => 'icon icon-edit' if !@invoice.nil? && @invoice.editable_by?(User.current) %>
  <%= link_to_if_authorized l(:label_invoice_pdf), {:controller => 'invoices', :action => 'show', :id => @invoice, :format => 'pdf'}, :class => 'icon icon-pdf' unless @invoice.nil? %>
  <%= link_to l(:label_invoice_add_payment), new_invoice_payment_path(:invoice_id => @invoice), :class => 'icon icon-add-payment' if User.current.allowed_to?(:edit_invoice_payments, @project) %>
	<%= link_to l(:button_delete), {:controller => 'invoices', :action => 'destroy', :id => @invoice}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' if  !@invoice.nil? && @invoice.destroyable_by?(User.current) %>
</div>

<h2><%= "#{@invoice.is_estimate? ? l(:label_estimate) : l(:label_invoice)} ##{@invoice.number}" %></h2>

<div class="issue invoice details <%= 'overdue' if @invoice.overdue? %>">
  <div class="subject">
    <h3><%= "#{@invoice.contact.name + ' - ' if @invoice.contact}#{price_to_currency(@invoice.amount, @invoice.currency, :converted => false)}#{' - ' + @invoice.subject unless @invoice.subject.blank?}" %></h3>
  </div>

  <p class="author">
    <%= authoring @invoice.created_at, @invoice.author %>.
    <% if @invoice.created_at != @invoice.updated_at %>
    <%= l(:label_updated_time, time_tag(@invoice.updated_at)).html_safe %>.
    <% end %>
  </p>

  <%= render :partial => 'invoices/attributes', :locals => {:invoice => @invoice} %>

  <hr />
  <p><strong><%= l(:label_invoice_lines) %></strong></p>
  <div class="invoice-lines">
  <%= render :partial => 'invoices/invoice_lines', :locals => {:invoice => @invoice} %>
  </div>

  <%= call_hook(:view_invoices_show_lines_bottom, :invoice => @invoice) %>
  <% if @invoice.attachments.any? -%>
  <hr />
  <%= link_to_attachments @invoice, :thumbnails => true %>
  <% end %>

</div>

<% if @payments.present? %>
  <div id="invoice_payments">
  <h3><%=l(:label_invoice_payment_plural)%></h3>
  <%= render :partial => 'invoice_payments/payments', :locals => { :payments => @payments} %>
    <% if User.current.allowed_to?(:edit_invoice_payments, @project) %>
      <p id="add_payment"><%= link_to l(:label_invoice_add_payment), new_invoice_payment_path(@invoice) %></p>
    <% end %>
  </div>
<% end %>


<div id="comments" style="margin-bottom:16px;">
<h3 class="comments"><%= l(:label_comment_plural) %></h3>
<% @comments.each do |comment| %>
    <% next if comment.new_record? %>
    <div class="contextual">
    <%= link_to_if_authorized image_tag('delete.png'), {:controller => 'invoice_comments', :action => 'destroy', :id => @invoice, :comment_id => comment},
                                                       :data => {:confirm => l(:text_are_you_sure)}, :method => :delete, :title => l(:button_delete) %>
    </div>
    <h4><%= avatar(comment.author, :size => "24") %><%= authoring comment.created_on, comment.author %></h4>
    <%= textilizable(comment.comments) %>
<% end if @comments.any? %>
</div>

<% if @invoice.commentable? %>
  <p><%= toggle_link l(:label_comment_add), "add_comment_form", :focus => "comment_comments" %></p>
  <%= form_tag({:controller => 'invoice_comments', :action => 'create', :id => @invoice}, :id => "add_comment_form", :style => "display:none;") do %>
    <div class="box">
        <%= text_area 'comment', 'comments', :cols => 80, :rows => 15, :class => 'wiki-edit' %>
        <%= wikitoolbar_for 'comment_comments' %>
    </div>
    <p><%= submit_tag l(:button_add) %></p>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <div class="contact-card small-card">
    <h3><%= l(:label_contact) %></h3>
    <%= render :partial => 'contacts/contact_card', :object => @invoice.contact %>
  </div>
  <%= render :partial => 'stat_invoiced' %>
  <%= render :partial => 'stat_status' %>
<% end if @invoice.contact %>

<% html_title "#{l(:label_invoice)} ##{@invoice.number}" %>

<% content_for :header_tags do %>
	<meta name = "format-detection" content = "telephone=no">
<% end %>