config/routes.rb
# This file is a part of Redmine Invoices (redmine_contacts_invoices) plugin,
# invoicing plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# https://www.redmineup.com/
#
# redmine_contacts_invoices is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts_invoices is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts_invoices.  If not, see <http://www.gnu.org/licenses/>.

resources :invoices do
  member do
    get :client_view
  end
  collection do
    get :auto_complete
    get :bulk_edit, :context_menu
    post :bulk_edit, :bulk_update
    delete :bulk_destroy
    get :recurring
  end
end

resources :recurring_invoices

resources :invoices do
  resources :invoice_payments, :as => :payments
end

resources :invoice_payments, :only => [:show, :index]
resources :invoice_comments, :only => [:create, :destroy]

resources :projects do
resources :invoices, :only => [:index, :new, :create]
end

match "invoice_time_entries/new", :controller => "invoice_time_entries", :action => 'new', :via => :get
match "invoice_time_entries/create", :controller => "invoice_time_entries", :action => 'create', :via => :post

app/views/layouts/invoices.pdf.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html class="<%= "preview" if @html_preview %>">
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <style type="text/css">
    .preview body {
      background-color: #f3f3f3;
    }

    div#toolbar {
      display: none;
      width: 21cm;
      margin: auto;
    }

    div#content {
      background-color: #FFFFFF;
      box-sizing: border-box;
      moz-box-sizing: border-box;
      webkit-box-sizing: border-box;
      color: black;
      font-family: "Lucida Grande", Helvetica, Arial, "Sans-Serif";
      font-size: 12px;
      overflow: hidden;
      position: relative;
      text-align: left;
    }


    div.pdf-toolbar { font-family: 'Lucida Grande', Helvetica, Arial, 'Sans-Serif'; }
    div.pdf-toolbar .buttons { float:right; margin-top: 10px; }
    div.pdf-toolbar .buttons form { display: inline; }
    div.pdf-toolbar .due-amount .small-text { margin-bottom: -1px; font-size: 11px; color: #666666; }
    div.pdf-toolbar .due-amount .amount { font-weight: bold; font-size: 20px; }

    @media screen {
      .preview div#toolbar {
        display: block;
        padding-bottom: 5px;
      }
      .preview div#content {
        margin: 0 auto;
        border: 1px solid #CBCBCB;
        padding: 2.1cm 2.2cm;
        width: 21cm;
        min-height: 29.7cm;
        margin: 2px 0px 0px;
        margin: auto;
      }

      .preview div.page-break {
        display: block;
        clear: both;
        page-break-after: always;
        height: 10px;
        border-top: 1px solid #CBCBCB;
        border-bottom: 1px solid #CBCBCB;
        margin: 50px -100px;
        background-color: #f3f3f3;
      }
    }

    @media print {
      .preview div#content {
        margin: 0 auto;
        padding: 2.1cm 2.2cm;
        width: 21cm;
        min-height: 29.7cm;
        margin: 2px 0px 0px;
        margin: auto;
      }
      div.page-break {
        display: block;
        clear: both;
        page-break-after: always;
      }

    }

  </style>
</head>
<body>


  <div id="toolbar" class="pdf-toolbar">
    <div class="buttons">
      <%= link_to  button_tag(l(:label_invoice_download_as_pdf), :type => "button"), client_view_invoice_path(@invoice, :token => @invoice.token, :format => :pdf) %>
      <%= link_to  button_tag(l(:label_invoice_print), :type => "button"), '#', :onclick => "window.print();" %>
    </div>
  </div>

  <div id="content">
    <%= yield %>
  </div>
</body>
</html>